/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThresholdsRouteImport } from './routes/thresholds'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as FieldsRouteImport } from './routes/fields'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const ThresholdsRoute = ThresholdsRouteImport.update({
  id: '/thresholds',
  path: '/thresholds',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldsRoute = FieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/fields': typeof FieldsRoute
  '/sensors': typeof SensorsRoute
  '/thresholds': typeof ThresholdsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/fields': typeof FieldsRoute
  '/sensors': typeof SensorsRoute
  '/thresholds': typeof ThresholdsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/fields': typeof FieldsRoute
  '/sensors': typeof SensorsRoute
  '/thresholds': typeof ThresholdsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/devices'
    | '/fields'
    | '/sensors'
    | '/thresholds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/devices'
    | '/fields'
    | '/sensors'
    | '/thresholds'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/devices'
    | '/fields'
    | '/sensors'
    | '/thresholds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DevicesRoute: typeof DevicesRoute
  FieldsRoute: typeof FieldsRoute
  SensorsRoute: typeof SensorsRoute
  ThresholdsRoute: typeof ThresholdsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thresholds': {
      id: '/thresholds'
      path: '/thresholds'
      fullPath: '/thresholds'
      preLoaderRoute: typeof ThresholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fields': {
      id: '/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof FieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  DevicesRoute: DevicesRoute,
  FieldsRoute: FieldsRoute,
  SensorsRoute: SensorsRoute,
  ThresholdsRoute: ThresholdsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
